- name: schema-validate
  hosts: localhost
  remote_user: ans
  vars:
    - work_dir: "/tmp"
    -   build_tag: "build-sphere-backend-{{ CI_COMMIT_SHORT_SHA }}"

  tasks:
    -   name: Определяем последнюю тестовую сборку
        raw: ls -d -r {{ work_dir }}/{{ build_tag }}_* | head -n  1
        register: build_dir_result

    -   name: Директория для проверок
        debug: var=build_dir_result.stdout_lines

    - raw: cd "{{ build_dir_result.stdout_lines[0] }}/app" && php8.2 bin/console doctrine:schema:validate --skip-sync
      register: schema_validate_result

    - name: "Вывод:"
      debug: var=schema_validate_result.stdout_lines
